require('dotenv').config();
const mongoose = require('mongoose');
const Career = require('./models/Career');
const LearningResource = require('./models/LearningResource');
const Project = require('./models/Project');

const careers = [
  {
    name: 'Frontend Developer',
    slug: 'frontend-developer',
    description: 'Frontend developers build user interfaces and interactive web experiences using HTML, CSS, and JavaScript frameworks.',
    icon: '🎨',
    averageSalary: '₹4-12 LPA (India) / $70-120K (US)',
    demandLevel: 'High',
    requiredSkills: [
      { skillName: 'HTML', category: 'Core', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'CSS', category: 'Core', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'JavaScript', category: 'Core', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'React', category: 'Framework', targetProficiency: 3, priority: 'Important' },
      { skillName: 'TypeScript', category: 'Language', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Git', category: 'Tools', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Responsive Design', category: 'Design', targetProficiency: 3, priority: 'Important' },
      { skillName: 'REST APIs', category: 'Integration', targetProficiency: 2, priority: 'Important' },
    ],
    responsibilities: [
      'Build and maintain web user interfaces',
      'Translate UI/UX designs into code',
      'Optimize applications for performance',
      'Collaborate with backend developers',
      'Write unit and integration tests',
      'Maintain cross-browser compatibility',
    ],
    sampleProjects: [
      'Portfolio website',
      'E-commerce product page',
      'Weather app with API',
      'Todo app with React',
      'Responsive landing page',
    ],
    learningPath: [
      'Master HTML & CSS fundamentals',
      'Learn JavaScript deeply',
      'Pick a framework (React recommended)',
      'Learn version control with Git',
      'Build projects and deploy them',
      'Learn TypeScript for larger projects',
    ],
    tags: ['web', 'javascript', 'react', 'css'],
  },
  {
    name: 'Backend Developer',
    slug: 'backend-developer',
    description: 'Backend developers build server-side logic, databases, APIs, and ensure applications run smoothly behind the scenes.',
    icon: '⚙️',
    averageSalary: '₹5-15 LPA (India) / $80-140K (US)',
    demandLevel: 'High',
    requiredSkills: [
      { skillName: 'Node.js', category: 'Runtime', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'JavaScript', category: 'Language', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Express.js', category: 'Framework', targetProficiency: 3, priority: 'Important' },
      { skillName: 'MongoDB', category: 'Database', targetProficiency: 3, priority: 'Important' },
      { skillName: 'SQL', category: 'Database', targetProficiency: 3, priority: 'Important' },
      { skillName: 'REST APIs', category: 'Architecture', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'Git', category: 'Tools', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Authentication & Security', category: 'Security', targetProficiency: 3, priority: 'Important' },
    ],
    responsibilities: [
      'Design and implement RESTful APIs',
      'Manage databases and data models',
      'Implement authentication and authorization',
      'Optimize server performance',
      'Write server-side business logic',
      'Deploy and maintain backend services',
    ],
    sampleProjects: [
      'REST API for a blog',
      'User authentication system',
      'E-commerce backend',
      'Real-time chat server',
      'Task management API',
    ],
    learningPath: [
      'Learn a backend language (Node.js/Python)',
      'Understand databases (SQL + NoSQL)',
      'Build RESTful APIs',
      'Learn authentication (JWT, OAuth)',
      'Practice with Docker and deployment',
      'Understand system design basics',
    ],
    tags: ['nodejs', 'api', 'database', 'server'],
  },
  {
    name: 'Full-Stack Developer',
    slug: 'fullstack-developer',
    description: 'Full-stack developers work on both frontend and backend, building complete end-to-end web applications.',
    icon: '🔥',
    averageSalary: '₹6-18 LPA (India) / $90-150K (US)',
    demandLevel: 'High',
    requiredSkills: [
      { skillName: 'HTML', category: 'Frontend', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'CSS', category: 'Frontend', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'JavaScript', category: 'Core', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'React', category: 'Frontend', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Node.js', category: 'Backend', targetProficiency: 3, priority: 'Important' },
      { skillName: 'MongoDB', category: 'Database', targetProficiency: 3, priority: 'Important' },
      { skillName: 'REST APIs', category: 'Integration', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Git', category: 'Tools', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Deployment', category: 'DevOps', targetProficiency: 2, priority: 'Nice-to-have' },
    ],
    responsibilities: [
      'Develop both frontend and backend features',
      'Design database schemas',
      'Build and consume APIs',
      'Deploy applications to cloud platforms',
      'Participate in all phases of development',
      'Troubleshoot full-stack issues',
    ],
    sampleProjects: [
      'Full-stack blog with auth',
      'Social media clone',
      'E-commerce app',
      'Project management tool',
      'Real-time collaborative app',
    ],
    learningPath: [
      'Build frontend skills first (HTML/CSS/JS)',
      'Learn React for dynamic UIs',
      'Master Node.js and Express',
      'Work with databases (MongoDB + SQL)',
      'Build full-stack projects end-to-end',
      'Learn deployment (Vercel, Railway, AWS)',
    ],
    tags: ['fullstack', 'react', 'nodejs', 'mongodb'],
  },
  {
    name: 'Data Analyst',
    slug: 'data-analyst',
    description: 'Data analysts collect, process, and analyze data to help organizations make data-driven decisions.',
    icon: '📊',
    averageSalary: '₹4-12 LPA (India) / $65-110K (US)',
    demandLevel: 'High',
    requiredSkills: [
      { skillName: 'Python', category: 'Language', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'SQL', category: 'Database', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'Excel', category: 'Tools', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Tableau', category: 'Visualization', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Pandas', category: 'Library', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Statistics', category: 'Math', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Data Visualization', category: 'Skills', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Power BI', category: 'Tools', targetProficiency: 2, priority: 'Nice-to-have' },
    ],
    responsibilities: [
      'Clean and process large datasets',
      'Create visualizations and dashboards',
      'Identify trends and patterns in data',
      'Write SQL queries for data extraction',
      'Prepare reports for stakeholders',
      'Collaborate with business teams',
    ],
    sampleProjects: [
      'Sales trend analysis dashboard',
      'Customer segmentation analysis',
      'Web scraping and data pipeline',
      'COVID-19 data visualization',
      'Stock market analysis',
    ],
    learningPath: [
      'Learn Python basics',
      'Master SQL for data querying',
      'Study statistics fundamentals',
      'Learn Pandas and NumPy',
      'Practice data visualization with Matplotlib/Seaborn',
      'Build dashboards with Tableau or Power BI',
    ],
    tags: ['data', 'python', 'sql', 'analytics'],
  },
  {
    name: 'Cybersecurity Analyst',
    slug: 'cybersecurity-analyst',
    description: 'Cybersecurity analysts protect organizations from cyber threats, monitor systems, and respond to security incidents.',
    icon: '🔐',
    averageSalary: '₹5-15 LPA (India) / $75-130K (US)',
    demandLevel: 'High',
    requiredSkills: [
      { skillName: 'Networking', category: 'Fundamentals', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'Linux', category: 'OS', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Security Protocols', category: 'Security', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Python', category: 'Language', targetProficiency: 2, priority: 'Important' },
      { skillName: 'Threat Analysis', category: 'Skills', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'SIEM Tools', category: 'Tools', targetProficiency: 2, priority: 'Important' },
      { skillName: 'Cryptography', category: 'Security', targetProficiency: 2, priority: 'Important' },
      { skillName: 'Ethical Hacking', category: 'Skills', targetProficiency: 2, priority: 'Nice-to-have' },
    ],
    responsibilities: [
      'Monitor network traffic for threats',
      'Conduct vulnerability assessments',
      'Respond to security incidents',
      'Implement security policies',
      'Perform security audits',
      'Educate staff on security practices',
    ],
    sampleProjects: [
      'Network vulnerability scanner',
      'Password strength analyzer',
      'Intrusion detection system simulation',
      'Security audit report',
      'CTF challenge writeup',
    ],
    learningPath: [
      'Learn networking fundamentals (TCP/IP)',
      'Master Linux command line',
      'Study security certifications (CompTIA Security+)',
      'Practice with ethical hacking tools',
      'Participate in CTF competitions',
      'Learn SIEM and monitoring tools',
    ],
    tags: ['security', 'networking', 'linux', 'ethical-hacking'],
  },
  {
    name: 'UI/UX Designer',
    slug: 'uiux-designer',
    description: 'UI/UX designers create intuitive, accessible, and visually appealing user experiences for digital products.',
    icon: '✏️',
    averageSalary: '₹4-12 LPA (India) / $65-120K (US)',
    demandLevel: 'Medium',
    requiredSkills: [
      { skillName: 'Figma', category: 'Tools', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'UI Design Principles', category: 'Design', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'UX Research', category: 'Research', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Prototyping', category: 'Skills', targetProficiency: 3, priority: 'Important' },
      { skillName: 'User Testing', category: 'Research', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Typography & Color', category: 'Design', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Wireframing', category: 'Skills', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'HTML/CSS (basic)', category: 'Technical', targetProficiency: 2, priority: 'Nice-to-have' },
    ],
    responsibilities: [
      'Create wireframes and prototypes',
      'Conduct user research and testing',
      'Design user flows and information architecture',
      'Collaborate with developers on implementation',
      'Maintain design systems',
      'Ensure accessibility standards',
    ],
    sampleProjects: [
      'Mobile app redesign',
      'Design system creation',
      'E-commerce UX audit',
      'Onboarding flow design',
      'Accessibility-focused website redesign',
    ],
    learningPath: [
      'Learn design principles (color, typography, layout)',
      'Master Figma',
      'Study UX fundamentals (user research, personas)',
      'Practice wireframing and prototyping',
      'Build a portfolio with case studies',
      'Learn about accessibility (WCAG)',
    ],
    tags: ['design', 'figma', 'ux', 'ui'],
  },
  {
    name: 'Cloud Engineer',
    slug: 'cloud-engineer',
    description: 'Cloud engineers design, build, and maintain cloud infrastructure and services using platforms like AWS, Azure, or GCP.',
    icon: '☁️',
    averageSalary: '₹8-20 LPA (India) / $100-160K (US)',
    demandLevel: 'High',
    requiredSkills: [
      { skillName: 'AWS/Azure/GCP', category: 'Cloud', targetProficiency: 4, priority: 'Essential' },
      { skillName: 'Linux', category: 'OS', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Docker', category: 'Containers', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Kubernetes', category: 'Orchestration', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Networking', category: 'Fundamentals', targetProficiency: 3, priority: 'Essential' },
      { skillName: 'Infrastructure as Code', category: 'DevOps', targetProficiency: 3, priority: 'Important' },
      { skillName: 'CI/CD Pipelines', category: 'DevOps', targetProficiency: 3, priority: 'Important' },
      { skillName: 'Python/Bash scripting', category: 'Scripting', targetProficiency: 2, priority: 'Important' },
    ],
    responsibilities: [
      'Design and deploy cloud infrastructure',
      'Implement CI/CD pipelines',
      'Monitor cloud performance and costs',
      'Ensure security and compliance',
      'Migrate on-premise systems to cloud',
      'Configure auto-scaling and high availability',
    ],
    sampleProjects: [
      'Deploy a web app on AWS',
      'Set up a CI/CD pipeline with GitHub Actions',
      'Build a serverless API',
      'Containerize applications with Docker',
      'Create an Infrastructure-as-Code template',
    ],
    learningPath: [
      'Learn Linux and networking basics',
      'Get started with one cloud provider (AWS recommended)',
      'Learn Docker and containers',
      'Study Kubernetes for orchestration',
      'Learn Terraform for Infrastructure as Code',
      'Obtain a cloud certification (AWS Solutions Architect)',
    ],
    tags: ['cloud', 'aws', 'devops', 'kubernetes'],
  },
];

const learningResources = [
  // Frontend
  {
    title: 'The Odin Project - Web Development',
    description: 'Free, open-source curriculum for learning web development from scratch.',
    url: 'https://www.theodinproject.com',
    provider: 'The Odin Project',
    skillCategory: 'Frontend',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
    resourceType: 'Course',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 200,
    rating: 4.9,
    careerGoals: ['Frontend Developer', 'Full-Stack Developer'],
  },
  {
    title: 'freeCodeCamp - Responsive Web Design',
    description: 'Learn HTML, CSS, and responsive design principles through interactive challenges.',
    url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    provider: 'freeCodeCamp',
    skillCategory: 'Frontend',
    skills: ['HTML', 'CSS', 'Responsive Design'],
    resourceType: 'Course',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 40,
    rating: 4.8,
    careerGoals: ['Frontend Developer', 'Full-Stack Developer', 'UI/UX Designer'],
  },
  {
    title: 'JavaScript.info - Modern JavaScript Tutorial',
    description: 'Comprehensive modern JavaScript tutorial from basics to advanced.',
    url: 'https://javascript.info',
    provider: 'javascript.info',
    skillCategory: 'JavaScript',
    skills: ['JavaScript', 'TypeScript'],
    resourceType: 'Tutorial',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 60,
    rating: 4.9,
    careerGoals: ['Frontend Developer', 'Backend Developer', 'Full-Stack Developer'],
  },
  {
    title: 'React Official Documentation',
    description: 'Official React documentation with interactive examples and tutorials.',
    url: 'https://react.dev',
    provider: 'Meta',
    skillCategory: 'Frontend',
    skills: ['React', 'JavaScript'],
    resourceType: 'Documentation',
    difficulty: 'Intermediate',
    isFree: true,
    estimatedHours: 30,
    rating: 4.8,
    careerGoals: ['Frontend Developer', 'Full-Stack Developer'],
  },
  // Backend
  {
    title: 'Node.js Official Documentation',
    description: 'Official documentation for Node.js — the JavaScript runtime for backend.',
    url: 'https://nodejs.org/en/docs',
    provider: 'Node.js Foundation',
    skillCategory: 'Backend',
    skills: ['Node.js', 'JavaScript'],
    resourceType: 'Documentation',
    difficulty: 'Intermediate',
    isFree: true,
    estimatedHours: 20,
    rating: 4.5,
    careerGoals: ['Backend Developer', 'Full-Stack Developer'],
  },
  {
    title: 'MongoDB University - MongoDB Basics',
    description: 'Free courses on MongoDB from the official MongoDB University.',
    url: 'https://university.mongodb.com',
    provider: 'MongoDB',
    skillCategory: 'Database',
    skills: ['MongoDB', 'NoSQL'],
    resourceType: 'Course',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 15,
    rating: 4.6,
    careerGoals: ['Backend Developer', 'Full-Stack Developer'],
  },
  // Data
  {
    title: 'Kaggle - Python & Data Science Courses',
    description: 'Free micro-courses on Python, Pandas, SQL, Machine Learning by Kaggle.',
    url: 'https://www.kaggle.com/learn',
    provider: 'Kaggle',
    skillCategory: 'Data Science',
    skills: ['Python', 'Pandas', 'SQL', 'Statistics', 'Data Visualization'],
    resourceType: 'Course',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 50,
    rating: 4.7,
    careerGoals: ['Data Analyst'],
  },
  {
    title: 'SQLZoo - Interactive SQL Tutorial',
    description: 'Learn SQL interactively with real database exercises.',
    url: 'https://sqlzoo.net',
    provider: 'SQLZoo',
    skillCategory: 'Database',
    skills: ['SQL'],
    resourceType: 'Practice',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 15,
    rating: 4.5,
    careerGoals: ['Data Analyst', 'Backend Developer'],
  },
  // Security
  {
    title: 'TryHackMe - Cybersecurity Learning Platform',
    description: 'Hands-on cybersecurity training through virtual rooms and challenges.',
    url: 'https://tryhackme.com',
    provider: 'TryHackMe',
    skillCategory: 'Cybersecurity',
    skills: ['Networking', 'Linux', 'Security Protocols', 'Ethical Hacking', 'Threat Analysis'],
    resourceType: 'Practice',
    difficulty: 'Beginner',
    isFree: false,
    estimatedHours: 100,
    rating: 4.8,
    careerGoals: ['Cybersecurity Analyst'],
  },
  {
    title: 'CompTIA Security+ Study Guide',
    description: 'Study resources for the CompTIA Security+ certification exam.',
    url: 'https://www.comptia.org/certifications/security',
    provider: 'CompTIA',
    skillCategory: 'Cybersecurity',
    skills: ['Security Protocols', 'Cryptography', 'Threat Analysis', 'SIEM Tools'],
    resourceType: 'Book',
    difficulty: 'Intermediate',
    isFree: false,
    estimatedHours: 80,
    rating: 4.6,
    careerGoals: ['Cybersecurity Analyst'],
  },
  // Design
  {
    title: 'Figma - Official Learning Resources',
    description: 'Official Figma tutorials and design courses for UI/UX designers.',
    url: 'https://help.figma.com/hc/en-us/categories/360002042553',
    provider: 'Figma',
    skillCategory: 'UI/UX Design',
    skills: ['Figma', 'Prototyping', 'Wireframing', 'UI Design Principles'],
    resourceType: 'Tutorial',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 20,
    rating: 4.7,
    careerGoals: ['UI/UX Designer'],
  },
  {
    title: 'Google UX Design Certificate (Coursera)',
    description: 'Professional certificate from Google covering UX research, design thinking, and Figma.',
    url: 'https://www.coursera.org/professional-certificates/google-ux-design',
    provider: 'Google / Coursera',
    skillCategory: 'UI/UX Design',
    skills: ['UX Research', 'User Testing', 'Prototyping', 'Wireframing', 'UI Design Principles'],
    resourceType: 'Course',
    difficulty: 'Beginner',
    isFree: false,
    estimatedHours: 200,
    rating: 4.8,
    careerGoals: ['UI/UX Designer'],
  },
  // Cloud
  {
    title: 'AWS Training & Certification - Free Tier',
    description: 'Official AWS free training resources and hands-on labs.',
    url: 'https://aws.amazon.com/training/free-digital-training/',
    provider: 'Amazon Web Services',
    skillCategory: 'Cloud',
    skills: ['AWS/Azure/GCP', 'Cloud', 'Networking'],
    resourceType: 'Course',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 40,
    rating: 4.6,
    careerGoals: ['Cloud Engineer'],
  },
  {
    title: 'Docker Official Getting Started Guide',
    description: 'Official Docker tutorial for containerizing applications.',
    url: 'https://docs.docker.com/get-started/',
    provider: 'Docker',
    skillCategory: 'DevOps',
    skills: ['Docker', 'Kubernetes', 'CI/CD Pipelines'],
    resourceType: 'Documentation',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 10,
    rating: 4.5,
    careerGoals: ['Cloud Engineer', 'Backend Developer'],
  },
  // General
  {
    title: 'Git & GitHub - Official Documentation',
    description: 'Official Git documentation and GitHub guides for version control.',
    url: 'https://docs.github.com/en/get-started',
    provider: 'GitHub',
    skillCategory: 'Tools',
    skills: ['Git', 'GitHub'],
    resourceType: 'Documentation',
    difficulty: 'Beginner',
    isFree: true,
    estimatedHours: 5,
    rating: 4.7,
    careerGoals: ['Frontend Developer', 'Backend Developer', 'Full-Stack Developer', 'Data Analyst', 'Cybersecurity Analyst'],
  },
];

const projects = [
  // Frontend - Beginner
  {
    title: 'Personal Portfolio Website',
    description: 'Build a responsive portfolio website showcasing your projects, skills, and contact information.',
    careerGoals: ['Frontend Developer', 'Full-Stack Developer', 'UI/UX Designer'],
    skillsRequired: ['HTML', 'CSS', 'JavaScript'],
    difficulty: 'Beginner',
    techStack: ['HTML5', 'CSS3', 'JavaScript', 'GitHub Pages'],
    implementationSteps: [
      'Create the HTML structure with sections: hero, about, projects, contact',
      'Style with CSS using flexbox/grid for layout',
      'Add smooth scroll and simple animations with JavaScript',
      'Make it responsive for mobile devices',
      'Deploy on GitHub Pages',
    ],
    expectedOutcome: 'A live, public portfolio website that demonstrates your frontend skills.',
    estimatedHours: 15,
    tags: ['portfolio', 'html', 'css', 'beginner'],
  },
  {
    title: 'Weather App',
    description: 'Create a weather application that fetches real-time data from a public weather API and displays it clearly.',
    careerGoals: ['Frontend Developer', 'Full-Stack Developer'],
    skillsRequired: ['HTML', 'CSS', 'JavaScript', 'REST APIs'],
    difficulty: 'Beginner',
    techStack: ['HTML5', 'CSS3', 'JavaScript', 'OpenWeatherMap API'],
    implementationSteps: [
      'Register for a free OpenWeatherMap API key',
      'Build the UI with search input and weather display',
      'Use fetch() to call the weather API',
      'Display temperature, conditions, and icons',
      'Handle errors for invalid cities',
    ],
    expectedOutcome: 'A functional weather app that queries a real API and shows live weather data.',
    estimatedHours: 10,
    tags: ['api', 'javascript', 'beginner'],
  },
  // Frontend - Intermediate
  {
    title: 'React Task Manager',
    description: 'Build a full-featured task management application with React, including drag-and-drop, filtering, and local storage persistence.',
    careerGoals: ['Frontend Developer', 'Full-Stack Developer'],
    skillsRequired: ['React', 'JavaScript', 'CSS'],
    difficulty: 'Intermediate',
    techStack: ['React', 'React DnD', 'CSS Modules', 'LocalStorage'],
    implementationSteps: [
      'Set up a React project with Vite',
      'Create task components with CRUD operations',
      'Add drag-and-drop functionality',
      'Implement filtering by status and priority',
      'Persist data with localStorage',
      'Add due dates and reminder notifications',
    ],
    expectedOutcome: 'A polished task manager that demonstrates React state management and component design.',
    estimatedHours: 25,
    tags: ['react', 'intermediate', 'state-management'],
  },
  // Backend - Beginner
  {
    title: 'REST API for a Blog',
    description: 'Build a fully functional RESTful API for a blog platform with CRUD operations for posts and comments.',
    careerGoals: ['Backend Developer', 'Full-Stack Developer'],
    skillsRequired: ['Node.js', 'Express.js', 'MongoDB', 'REST APIs'],
    difficulty: 'Beginner',
    techStack: ['Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'Postman'],
    implementationSteps: [
      'Initialize Node.js project with Express',
      'Set up MongoDB with Mongoose models',
      'Create routes for posts: GET, POST, PUT, DELETE',
      'Add comments as nested resources',
      'Implement basic error handling',
      'Test all endpoints with Postman',
    ],
    expectedOutcome: 'A tested REST API with full CRUD operations, ready to connect to a frontend.',
    estimatedHours: 20,
    tags: ['nodejs', 'api', 'mongodb', 'beginner'],
  },
  // Backend - Intermediate
  {
    title: 'JWT Authentication System',
    description: 'Implement a secure user authentication system with registration, login, JWT tokens, and protected routes.',
    careerGoals: ['Backend Developer', 'Full-Stack Developer'],
    skillsRequired: ['Node.js', 'Express.js', 'MongoDB', 'Authentication & Security'],
    difficulty: 'Intermediate',
    techStack: ['Node.js', 'Express.js', 'MongoDB', 'bcryptjs', 'jsonwebtoken'],
    implementationSteps: [
      'Create User model with hashed passwords using bcrypt',
      'Build register and login endpoints',
      'Generate and validate JWT tokens',
      'Create middleware to protect routes',
      'Add refresh token functionality',
      'Implement rate limiting to prevent brute force',
    ],
    expectedOutcome: 'A secure authentication system that can be reused in any Node.js application.',
    estimatedHours: 20,
    tags: ['auth', 'jwt', 'security', 'intermediate'],
  },
  // Data - Beginner
  {
    title: 'Exploratory Data Analysis with Python',
    description: 'Perform a complete exploratory data analysis on a real public dataset using Python and Pandas.',
    careerGoals: ['Data Analyst'],
    skillsRequired: ['Python', 'Pandas', 'Data Visualization', 'Statistics'],
    difficulty: 'Beginner',
    techStack: ['Python', 'Pandas', 'Matplotlib', 'Seaborn', 'Jupyter Notebook'],
    implementationSteps: [
      'Download a dataset from Kaggle (e.g., Titanic or Iris)',
      'Load and inspect the data with Pandas',
      'Handle missing values and outliers',
      'Create visualizations to find patterns',
      'Write a summary report of your findings',
    ],
    expectedOutcome: 'A Jupyter notebook with clear analysis, visualizations, and insights from a real dataset.',
    estimatedHours: 15,
    tags: ['python', 'data', 'pandas', 'beginner'],
  },
  // Data - Intermediate
  {
    title: 'Sales Dashboard with Tableau',
    description: 'Build an interactive business dashboard in Tableau to visualize sales performance, trends, and KPIs.',
    careerGoals: ['Data Analyst'],
    skillsRequired: ['Tableau', 'Data Visualization', 'SQL', 'Statistics'],
    difficulty: 'Intermediate',
    techStack: ['Tableau Public', 'Excel', 'SQL'],
    implementationSteps: [
      'Prepare a sales dataset (CSV or SQL database)',
      'Connect Tableau to the data source',
      'Create KPI cards for revenue, units sold, growth',
      'Build bar charts, line charts, and maps',
      'Add interactive filters for date range and region',
      'Publish the dashboard to Tableau Public',
    ],
    expectedOutcome: 'A published, interactive sales dashboard accessible via Tableau Public.',
    estimatedHours: 20,
    tags: ['tableau', 'dashboard', 'data', 'intermediate'],
  },
  // Security - Beginner
  {
    title: 'Network Vulnerability Scanner',
    description: 'Build a Python script that scans a local network for open ports and identifies potential vulnerabilities.',
    careerGoals: ['Cybersecurity Analyst'],
    skillsRequired: ['Python', 'Networking', 'Linux'],
    difficulty: 'Beginner',
    techStack: ['Python', 'Socket library', 'Linux terminal'],
    implementationSteps: [
      'Learn TCP/UDP socket basics in Python',
      'Write a port scanner for a given IP range',
      'Identify common services from port numbers',
      'Log results to a report file',
      'Run only on networks you own or have permission to scan',
    ],
    expectedOutcome: 'A functional port scanner script with a generated security report.',
    estimatedHours: 15,
    tags: ['python', 'security', 'networking', 'beginner'],
  },
  // Design - Beginner
  {
    title: 'Mobile App UI Design in Figma',
    description: 'Design a complete mobile application UI for a fitness tracking app in Figma.',
    careerGoals: ['UI/UX Designer'],
    skillsRequired: ['Figma', 'UI Design Principles', 'Wireframing', 'Typography & Color'],
    difficulty: 'Beginner',
    techStack: ['Figma'],
    implementationSteps: [
      'Research competing fitness apps for inspiration',
      'Create user personas and user flows',
      'Sketch wireframes for main screens',
      'Design high-fidelity screens in Figma',
      'Add interactions and create a clickable prototype',
      'Conduct a quick user test with 3 people',
    ],
    expectedOutcome: 'A polished Figma prototype ready to present as a portfolio case study.',
    estimatedHours: 20,
    tags: ['figma', 'design', 'mobile', 'beginner'],
  },
  // Cloud - Intermediate
  {
    title: 'Deploy a Web App on AWS',
    description: 'Deploy a full-stack web application to AWS using EC2, S3, and RDS, with a load balancer and SSL.',
    careerGoals: ['Cloud Engineer'],
    skillsRequired: ['AWS/Azure/GCP', 'Linux', 'Networking', 'Docker'],
    difficulty: 'Intermediate',
    techStack: ['AWS EC2', 'AWS S3', 'AWS RDS', 'Nginx', 'Docker'],
    implementationSteps: [
      'Create an AWS account and set up IAM roles',
      'Launch an EC2 instance and configure security groups',
      'Install Docker and deploy the app container',
      'Set up RDS for the database',
      'Configure S3 for static assets',
      'Set up a load balancer and SSL certificate',
    ],
    expectedOutcome: 'A live, deployed web application running on AWS with SSL, accessible via a public URL.',
    estimatedHours: 30,
    tags: ['aws', 'cloud', 'docker', 'intermediate'],
  },
  // Full-Stack - Advanced
  {
    title: 'Real-Time Chat Application',
    description: 'Build a fully functional real-time chat app with rooms, user authentication, file sharing, and online presence indicators.',
    careerGoals: ['Full-Stack Developer', 'Backend Developer'],
    skillsRequired: ['Node.js', 'React', 'MongoDB', 'REST APIs', 'JavaScript'],
    difficulty: 'Advanced',
    techStack: ['React', 'Node.js', 'Socket.io', 'MongoDB', 'Redis', 'JWT'],
    implementationSteps: [
      'Set up backend with Express and Socket.io',
      'Implement JWT authentication',
      'Create chat rooms and direct messages',
      'Build the React frontend with real-time updates',
      'Add online presence (user online/offline)',
      'Implement file upload to cloud storage',
      'Deploy with Redis for session management',
    ],
    expectedOutcome: 'A production-quality real-time chat app demonstrating advanced full-stack skills.',
    estimatedHours: 60,
    tags: ['realtime', 'socket.io', 'fullstack', 'advanced'],
  },
];

const seedDB = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/skillbridge';
    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Career.deleteMany({});
    await LearningResource.deleteMany({});
    await Project.deleteMany({});
    console.log('🗑️  Cleared existing data');

    // Insert seed data
    await Career.insertMany(careers);
    console.log(`✅ Inserted ${careers.length} careers`);

    await LearningResource.insertMany(learningResources);
    console.log(`✅ Inserted ${learningResources.length} learning resources`);

    await Project.insertMany(projects);
    console.log(`✅ Inserted ${projects.length} projects`);

    console.log('\n🎉 Database seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
};

seedDB();
